debug: true
server:
  port:
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name:
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com/qozvfqhy
    username: qozvfqhy
    password: pXPM03snq316mHcw-J-NCd9A8QToGgu5

  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR